### ISSUE TITLE
What is the order of photos shown in Gallery

### ISSUE THREAD

**Issue by Mr-Anonymous** [DmcSDK/cordova-plugin-mediaPicker#70]
What is the order of photos that are shown in the gallery list? Does it show the recent photos at the top and the older ones at the bottom (or) is it the other way around? One of my user reported that the photos are not showing in order. She said yesterday's photos should be at the top but she had to scroll down all the way to middle of her album to view the photos from yesterday. Why would that be?

She is using:

```
OS: android 9 
Browser: chrome 72.0.3626.105 
Device: android 
```

**Comment by DmcSDK** [comment]
I don't think this will happen.
because Gallery  Sort order by added date in android.
Android code：`MediaStore.Files.FileColumns.DATE_ADDED + " DESC" // Sort order.`
android doc:
public static final String DATE_ADDED

The time the file was added to the media provider Units are seconds since 1970.

Type: INTEGER (long)

Constant Value: "date_added"

**Comment by Mr-Anonymous** [comment]
Thank you confirming that @DmcSDK 

What I assume could be the issue here is, since the Android gallery's default option is set as 'all images', the user might be confused thinking it is mixing up the photos in different order. We have requested the user to select the album if she only wants to select the photos from her camera instead of viewing all photos that includes downloads, whatsapp, etc etc. Hopefully that fixes it. 

Thank you for your support.
